<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>enaml</string>
	</array>
	<key>name</key>
	<string>Enaml</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Identifier</string>
			<key>match</key>
			<string>^\s*(id):\s*([A-Za-z_][A-Za-z0-9_]*)\s*$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Declaration</string>
			<key>match</key>
			<string>^(enamldef)\s*([A-Za-z_][A-Za-z0-9_]*)\((.*?)\):\s*$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Declaration with id</string>
			<key>match</key>
			<string>^(enamldef)\s*([A-Za-z_][A-Za-z0-9_]*)\((.*?)\):\s*([A-Za-z_][A-Za-z0-9_]*):\s*$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(enamldef)\s*([A-Za-z_][A-Za-z0-9_]*)\((.*?)\):\s*([A-Za-z_][A-Za-z0-9_]*):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Declaration one liner with id</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(enamldef)\s*([A-Za-z_][A-Za-z0-9_]*)\((.*?)\):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Declaration one liner</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Instantiation</string>
			<key>match</key>
			<string>^\s*([A-Za-z_][A-Za-z0-9_]*):\s*$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Instantiation with id</string>
			<key>match</key>
			<string>^\s*([A-Za-z_][A-Za-z0-9_]*):\s*([A-Za-z_][A-Za-z0-9_]*):\s*$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([A-Za-z_][A-Za-z0-9_]*):\s*([A-Za-z_][A-Za-z0-9_]*):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Instantiation one liner with id</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([A-Za-z_][A-Za-z0-9_]*):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Instantiation one liner</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Attribute Declaration</string>
			<key>match</key>
			<string>^\s*(attr|event)\s*([A-Za-z_][A-Za-z_0-9]*)\s*$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Attribute Declaration with Type</string>
			<key>match</key>
			<string>^\s*(attr|event)\s*([A-Za-z_][A-Za-z_0-9]*)\s*:\s*([A-Za-z_][A-Za-z_0-9]*)\s*$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(attr|event)\s*([A-Za-z_][A-Za-z_0-9]*)\s*(=|:=|&lt;&lt;|&gt;&gt;|::)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Attribute Declaration with Binding</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(attr|event)\s*([A-Za-z_][A-Za-z_0-9]*)\s*:\s*([A-Za-z_][A-Za-z_0-9]*)\s*(=|:=|&lt;&lt;|&gt;&gt;|::)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Attribute Declaration with Type and Binding</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([A-Za-z_][A-Za-z_0-9]*)\s*(=|:=|&lt;&lt;|&gt;&gt;|::)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Enaml Attribute Binding</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.python</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.enaml</string>
	<key>uuid</key>
	<string>df282ee7-7441-487e-9a58-bfebbd01a9ff</string>
</dict>
</plist>
